#!/bin/bash
# Example usage: gitpull ~/phd tools/yap yap
echo "*******************"
echo "This is gitpull."
echo ""
echo "We will clone the existing repository on the local filesystem $1,"
echo "  retain only the subfolder $2"
echo "  and save the resulting repository in $3"
echo "******************"
echo " Exit now if this is incorrect. Press any key to continue."
read answer

git clone --no-hardlinks $1 $3
cd $3
CURR=`pwd`
git filter-branch --subdirectory-filter $2 HEAD -- --all
git reset --hard
rm -rf .git/refs/original/
git reflog expire --expire=now --all 
git gc --aggressive --prune=now
cd $1
mv $2 $2-old
ln -s $CURR $2
