#!/bin/bash
if [ "$1" = "-h" ]; then
echo "This is grepf, a utility to combine find with grep"
echo "Usage: grepf filepattern [grepoptions] matchstrings"
exit 0
fi
find -name "$1" -exec grep --color -n -H  $2 $3 $4 {} \;
