#!/bin/bash

if [ "$1" = "-h" ]; then
  echo "This is utilities, a utility that lists utilities"
  echo "Usage: utilities"
fi
  
for f in `find $UTILITIES -maxdepth 1 -type f -perm -111 | grep -v "~"`
do
  base=`basename "$f"`
	echo -e "\033[32m$base \033[0m"
	if [ -f $UTILITIES/$base.man ]; then
	  grep "NAME" -A 1 $UTILITIES/$base.man | tail -n 1
  fi
done
